import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { X, ExternalLink } from 'lucide-react';
import { Button } from './ui/button';

interface InfoPanelProps {
  onClose: () => void;
}

export function InfoPanel({ onClose }: InfoPanelProps) {
  return (
    <div className="absolute inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-black/95 border-blue-500/30 text-white">
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between">
            <CardTitle className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-600 bg-clip-text text-transparent">
              UUON Pstudio
            </CardTitle>
            <Button
              onClick={onClose}
              variant="ghost"
              size="icon"
              className="text-gray-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </Button>
          </div>
        </CardHeader>

        <CardContent className="space-y-6 text-sm">
          {/* Organization */}
          <section className="border-b border-blue-500/30 pb-4">
            <h3 className="text-lg font-semibold text-blue-300 mb-3">Organization</h3>
            <div className="space-y-2 text-gray-300">
              <p><strong className="text-blue-200">Publisher:</strong> UUON Pstudio</p>
            </div>
          </section>

          {/* Tools we use */}
          <section className="border-b border-blue-500/30 pb-4">
            <h3 className="text-lg font-semibold text-blue-300 mb-3">Built with</h3>
            <div className="flex flex-col gap-1">
              <a href="https://studio.tripo3d.ai/?via=phi1" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 flex items-center gap-1">
                <ExternalLink className="w-3 h-3" />
                Tripo3D — AI 3D model generation
              </a>
              <a href="https://replit.com/refer/phi1" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 flex items-center gap-1">
                <ExternalLink className="w-3 h-3" />
                Replit — built and hosted here
              </a>
            </div>
          </section>

          {/* About the Application */}
          <section className="border-b border-purple-500/30 pb-4">
            <h3 className="text-lg font-semibold text-purple-300 mb-3">About UUON Pstudio</h3>
            <p className="text-gray-300 leading-relaxed">
              UUON Pstudio is a multi-portal creative studio combining sacred geometry visualization,
              AI-powered 3D model generation, AI image creation, and parametric mathematics — all in one environment.
              Explore 26+ curve types, generate 3D models from text prompts via Tripo3D, create AI images via Pollinations.ai,
              and browse a gallery of 46 sacred symbol GLB models ready for export.
            </p>
          </section>

          {/* Mathematical Foundation */}
          <section className="border-b border-green-500/30 pb-4">
            <h3 className="text-lg font-semibold text-green-300 mb-3">Mathematical Foundation</h3>
            <div className="space-y-3 text-gray-300">
              <div>
                <h4 className="text-green-200 font-medium mb-1">Parametric Equations</h4>
                <p className="text-sm">
                  Curves are generated using parametric equations where each point is defined as:
                  <br />
                  <code className="bg-black/50 px-2 py-1 rounded text-green-400">P(t) = (x(t), y(t), z(t))</code>
                  <br />
                  where t is a parameter typically ranging from 0 to 2π or beyond.
                </p>
              </div>

              <div>
                <h4 className="text-green-200 font-medium mb-1">Curve Types (26+)</h4>
                <ul className="text-xs space-y-1 list-disc list-inside ml-2">
                  <li><strong>Hypocycloid:</strong> Generated by tracing a point on a circle rolling inside another circle</li>
                  <li><strong>Lissajous:</strong> x = A·sin(at + δ), y = B·sin(bt) - creates harmonic patterns</li>
                  <li><strong>Rose Curve:</strong> r = a·cos(kθ) - polar coordinate patterns</li>
                  <li><strong>Torus Knot:</strong> 3D knotted curves wrapping around a torus surface</li>
                  <li><strong>Klein Bottle:</strong> Non-orientable surface, 4D object projected into 3D</li>
                  <li><strong>Möbius Strip:</strong> Single-sided surface with one continuous edge</li>
                  <li>Plus: Spirals, helixes, epitrochoids, strange attractors, and more</li>
                </ul>
              </div>

              <div>
                <h4 className="text-green-200 font-medium mb-1">Vector Field Visualization</h4>
                <p className="text-sm">
                  Vector fields show the gradient flow around parametric curves, calculated using:
                  <br />
                  <code className="bg-black/50 px-2 py-1 rounded text-green-400">F(x,y,z) = ∇P(t)</code>
                  <br />
                  Visualized as arrows showing direction and magnitude of change.
                </p>
              </div>

              <div>
                <h4 className="text-green-200 font-medium mb-1">Key Parameters</h4>
                <ul className="text-xs space-y-1 ml-2">
                  <li><strong>k (frequency):</strong> Controls oscillation frequency and pattern repetition</li>
                  <li><strong>xyz Factors:</strong> Scale along each spatial dimension</li>
                  <li><strong>abc Factors:</strong> Shape modulation parameters</li>
                  <li><strong>Delta (δ):</strong> Phase shift for temporal offsets</li>
                  <li><strong>Complexity:</strong> Detail level and subdivision count</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Algorithms & Techniques */}
          <section className="border-b border-yellow-500/30 pb-4">
            <h3 className="text-lg font-semibold text-yellow-300 mb-3">Algorithms & Techniques</h3>
            <div className="space-y-2 text-gray-300 text-sm">
              <div>
                <strong className="text-yellow-200">Catmull-Rom Spline Interpolation:</strong> Smooth curve generation through control points using C1 continuous interpolation.
              </div>
              <div>
                <strong className="text-yellow-200">Tube Geometry Generation:</strong> Creates volumetric representations of curves by sweeping a circle along the path with adaptive subdivisions.
              </div>
              <div>
                <strong className="text-yellow-200">Vertex Color Mapping:</strong> Each vertex receives color based on parametric position, creating smooth gradients along curves.
              </div>
              <div>
                <strong className="text-yellow-200">Real-time Animation:</strong> Uses requestAnimationFrame for 60fps updates with time-based parameter modulation.
              </div>
              <div>
                <strong className="text-yellow-200">Export Formats:</strong>
                <ul className="list-disc list-inside ml-4 text-xs mt-1">
                  <li>GLB/GLTF: PBR materials, vertex colors, keyframe animations</li>
                  <li>USD: Pixar Universal Scene Description with metadata</li>
                  <li>STL: Solid geometry for 3D printing</li>
                  <li>JSON: Complete parameter state serialization</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Technology Stack */}
          <section className="border-b border-cyan-500/30 pb-4">
            <h3 className="text-lg font-semibold text-cyan-300 mb-3">Technology Stack</h3>
            <div className="grid grid-cols-2 gap-3 text-xs text-gray-300">
              <div>
                <strong className="text-cyan-200">Core Frameworks:</strong>
                <ul className="list-disc list-inside ml-2 mt-1">
                  <li>React 18 (MIT License)</li>
                  <li>TypeScript 5</li>
                  <li>Three.js r170 (MIT License)</li>
                  <li>React Three Fiber (MIT License)</li>
                </ul>
              </div>
              <div>
                <strong className="text-cyan-200">UI Libraries:</strong>
                <ul className="list-disc list-inside ml-2 mt-1">
                  <li>Radix UI (MIT License)</li>
                  <li>Tailwind CSS (MIT License)</li>
                  <li>Framer Motion (MIT License)</li>
                  <li>Lucide Icons (ISC License)</li>
                </ul>
              </div>
              <div>
                <strong className="text-cyan-200">AI Services:</strong>
                <ul className="list-disc list-inside ml-2 mt-1">
                  <li>Tripo3D — text-to-3D generation</li>
                  <li>Pollinations.ai — text-to-image</li>
                </ul>
              </div>
              <div>
                <strong className="text-cyan-200">Build Tools:</strong>
                <ul className="list-disc list-inside ml-2 mt-1">
                  <li>Vite (MIT License)</li>
                  <li>ESBuild (MIT License)</li>
                  <li>PostCSS (MIT License)</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Open Source Credits */}
          <section>
            <h3 className="text-lg font-semibold text-pink-300 mb-3">Open Source Credits</h3>
            <div className="space-y-2 text-xs text-gray-300">
              <p className="text-pink-200">This project is built on the shoulders of giants. Special thanks to:</p>
              <ul className="list-disc list-inside ml-2 space-y-1">
                <li><strong>Three.js Team</strong> (Ricardo Cabello, et al.) - 3D graphics engine</li>
                <li><strong>Poimandres Team</strong> (Paul Henschel, et al.) - React Three Fiber & Drei</li>
                <li><strong>Radix UI Team</strong> (Colm Tuite, et al.) - Accessible UI primitives</li>
                <li><strong>Tailwind Labs</strong> (Adam Wathan, et al.) - CSS framework</li>
                <li><strong>Tanner Linsley</strong> - TanStack React Query</li>
                <li><strong>Daishi Kato</strong> - Zustand state management</li>
                <li><strong>Evan Wallace</strong> - ESBuild bundler</li>
                <li><strong>Evan You & Vite Team</strong> - Build tooling</li>
                <li><strong>Colin McDonnell</strong> - Zod validation</li>
              </ul>
              <p className="text-pink-200 mt-3">All open source dependencies are used under their respective licenses (primarily MIT).</p>
            </div>
          </section>

          {/* Footer */}
          <div className="text-center text-xs text-gray-500 pt-4 border-t border-gray-700">
            <p>© 2025 UUON Pstudio</p>
            <p className="mt-1">Made with mathematics, code, and creativity</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
